name: Test - CheckStyle

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  REPOSITORY_NAME: taojintianxia_github_action

jobs:
  check-checkstyle:
    name: Test - CheckStyle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ env.REPOSITORY_NAME }}-maven-third-party-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ env.REPOSITORY_NAME }}-maven-third-party-
      - name: Run CheckStyle
        run: echo "we gonna win win win"
